# NumPy Array and Vectorization

## Introduction to NumPy and creating arrays.

##### # convention for importing numpy

In [1]:
import numpy as np

In [2]:
arr = [ 6 , 7 , 8 , 9 ]
print(type(arr))

<class 'list'>


In [3]:
a = np.array(arr)

In [4]:
print(type(a))

<class 'numpy.ndarray'>


In [5]:
print(a.shape)

(4,)


In [6]:
print(a.dtype)

int32


#### # get the dimension of a with ndim

In [7]:
print(a.ndim)

1


In [8]:
b = np.array([[ 1 , 2 , 3 ], [ 4 , 5 , 6 ]])

In [9]:
print(b)

[[1 2 3]
 [4 5 6]]


In [10]:
print(b.ndim)

2


In [11]:
b.shape

(2, 3)

#### # a 2x3 array with random values

#### Intra-operability of arrays and scalars

In [13]:
c = np.array([[ 9.0 , 8.0 , 7.0 ], [ 1.0 , 2.0 , 3.0 ]])
d = np.array([[ 4.0 , 5.0 , 6.0 ], [ 9.0 , 8.0 , 7.0 ]])

In [14]:
c + d

array([[13., 13., 13.],
       [10., 10., 10.]])

In [15]:
c * d

array([[36., 40., 42.],
       [ 9., 16., 21.]])

In [16]:
5 / d

array([[1.25      , 1.        , 0.83333333],
       [0.55555556, 0.625     , 0.71428571]])

In [17]:
c ** 2

array([[81., 64., 49.],
       [ 1.,  4.,  9.]])

In [18]:
e = np.array([[ 10 , 11 , 12 ],[ 13 , 14 , 15 ],
[ 16 , 17 , 18 ],[ 19 , 20 , 21 ]])

### #slicing

In [19]:
e[: 3 , : 2 ]

array([[10, 11],
       [13, 14],
       [16, 17]])

#### # integer indexing

In [20]:
e[[ 2 , 0 , 3 , 1 ],[ 2 , 1 , 0 , 2 ]]

array([18, 11, 19, 15])

#### #boolean indexing meeting a specified condition

In [21]:
e[e> 15 ]

array([16, 17, 18, 19, 20, 21])